version: "3"

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/:ro #database files called when the container is built and started for the first time
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    ports:
      - "8080:8080"

volumes:
  mysql-data: